CREATE TABLE Gare (
	id_gare INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id_gare),
	nom VARCHAR(50) NOT NULL UNIQUE,
	inter_gauche INTEGER,
	inter_droite INTEGER,
	dist_gauche INTEGER,
	dist_droite INTEGER,
	x INTEGER NOT NULL,
	z INTEGER NOT NULL);

CREATE TABLE Inter (
	id_inter INT UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id_inter),
	gare_n INTEGER,
	gare_s INTEGER,
	gare_e INTEGER,
	gare_o INTEGER);
