name: TGVcraft
main: com.github.Sraye25.TGVcraft
version: 1.0
description: Plugin de gestion de réseau de minecart
database: true

commands:
    tgvcraft:
        description: Commandes du plugin TGVcraft
        usage: /<command> [mode]
